import './globals.css'

import type {Metadata} from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {children?: React.ReactNode}) {
    return (
        <html lang='en'>
            <body className={'w-[800px] mx-auto'}>
                <header className='w-full flex justify-between h-10 bg-slate-800 p-2'>
                    <h1>WanderWell</h1>
                    <nav className='flex gap-6'>
                        <Link href='/'>Home</Link>
                    </nav>
                </header>
                <main className='w-full my-8'>{children}</main>
            </body>
        </html>
    )
}
