import './globals.css'

import type {Metadata} from 'next'

import {Header} from '@/lib/components/header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {children?: React.ReactNode}) {
    return (
        <html lang='en'>
            <body className={'w-[800px] mx-auto'}>
                <Header />
                <main className='w-full my-8'>{children}</main>
            </body>
        </html>
    )
}
